name: packer
on:
  push:
    branches:
      - 'main'
  schedule:
  - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PKR_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      PKR_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #Targets AWS accounts for Jenkins AMI's--in this case tvm-ci-prod, terraform-tvm, and octoml-sandbox
      PKR_VAR_target_accounts: '["477529581014", "649843420731", "186900524924"]'
    steps:
      -
        name: Pull repository
        uses: actions/checkout@v2
      - 
        name: Build AWS base AMI
        uses: hashicorp/packer-github-actions@master
        env:
          WORKSPACE_DIR: jenkins-agents/stock
          PKR_VAR_image_prefix: ci-base
        with:
          command: build
          target: base-images/aws
      - 
        name: Build stock Jenkins agent
        uses: hashicorp/packer-github-actions@master
        env:
          WORKSPACE_DIR: jenkins-agents/stock
          PKR_VAR_source_image_family: ci-base
          PKR_VAR_image_prefix: jenkins-stock-agent
        with:
          command: build
          target: jenkins-agents/stock
      - 
        name: Build GPU Jenkins agent
        uses: hashicorp/packer-github-actions@master
        env:
          WORKSPACE_DIR: jenkins-agents/stock
          PKR_VAR_source_image_family: jenkins-stock-agent
          PKR_VAR_image_prefix: jenkins-gpu-agent
          PKR_VAR_nvidia_driver_version: "460.80"
          PKR_VAR_nvidia_driver_base_url: "https://us.download.nvidia.com/XFree86/Linux-x86_64"
        with:
          command: build
          target: jenkins-agents/gpu
